#!/usr/bin/env python3
"""Generate examples/refs/ref-fdpass.md — the fd-passing (sendmsg + SCM_RIGHTS)
ABI reference, x86-64 Linux, from LOCAL sources only (no network).

Sources, per the refs discipline:
  - syscall numbers: /usr/include/x86_64-linux-gnu/asm/unistd_64.h (__NR_*)
  - constants SOL_SOCKET / SCM_RIGHTS: Python `socket` module
  - struct msghdr / cmsghdr offsets+sizes: ctypes field layout (the platform's
    own C ABI, computed — never hand-typed)
  - CMSG_* alignment math: derived here, cross-checked against Python's
    socket.CMSG_LEN / CMSG_SPACE

Re-run to re-derive; every row names its source. `python3 gen-fdpass.py`.
"""
import ctypes
import os
import re
import socket

HERE = os.path.dirname(os.path.abspath(__file__))
UNISTD = "/usr/include/x86_64-linux-gnu/asm/unistd_64.h"


def nr(name):
    """Read a __NR_<name> syscall number from the local unistd header."""
    with open(UNISTD) as f:
        m = re.search(rf"#define __NR_{name}\s+(\d+)", f.read())
    return int(m.group(1)) if m else None


# --- struct layouts via ctypes: the platform computes its own offsets --------
class iovec(ctypes.Structure):
    _fields_ = [("iov_base", ctypes.c_void_p), ("iov_len", ctypes.c_size_t)]


class msghdr(ctypes.Structure):
    _fields_ = [
        ("msg_name", ctypes.c_void_p),
        ("msg_namelen", ctypes.c_uint),      # socklen_t
        ("msg_iov", ctypes.c_void_p),
        ("msg_iovlen", ctypes.c_size_t),
        ("msg_control", ctypes.c_void_p),
        ("msg_controllen", ctypes.c_size_t),
        ("msg_flags", ctypes.c_int),
    ]


class cmsghdr(ctypes.Structure):
    _fields_ = [
        ("cmsg_len", ctypes.c_size_t),
        ("cmsg_level", ctypes.c_int),
        ("cmsg_type", ctypes.c_int),
    ]


def layout(struct):
    return [(n, getattr(struct, n).offset, getattr(struct, n).size)
            for n, _ in struct._fields_]


# CMSG_DATA on this platform sits right after the header (sizeof padded).
CMSG_HDR_SIZE = ctypes.sizeof(cmsghdr)          # 16 on LP64
SIZEOF_SIZE_T = ctypes.sizeof(ctypes.c_size_t)  # 8


def cmsg_align(n):
    return (n + SIZEOF_SIZE_T - 1) & ~(SIZEOF_SIZE_T - 1)


def cmsg_len(n):      # bytes of header+data to put in cmsg_len
    return cmsg_align(CMSG_HDR_SIZE) + n


def cmsg_space(n):    # bytes to reserve in the control buffer
    return cmsg_align(n) + cmsg_align(CMSG_HDR_SIZE)


def tbl(rows):
    return "\n".join("| " + " | ".join(str(c) for c in r) + " |" for r in rows)


ONE_FD = ctypes.sizeof(ctypes.c_int)  # payload = one int fd = 4 bytes

# cross-check the CMSG math against Python's own macros
assert cmsg_len(ONE_FD) == socket.CMSG_LEN(ONE_FD), "CMSG_LEN drift"
assert cmsg_space(ONE_FD) == socket.CMSG_SPACE(ONE_FD), "CMSG_SPACE drift"

doc = f"""<!-- GENERATED by examples/refs/gen-fdpass.py — do not hand-edit; re-run to refresh. -->
# ref: fd-passing (sendmsg + SCM_RIGHTS) — x86-64 Linux

Derived locally by `gen-fdpass.py`. Passing an fd is `sendmsg(2)` with a
control message of level `SOL_SOCKET`, type `SCM_RIGHTS`, whose data is the
int fd(s). The floor builds the `msghdr` + `cmsghdr` in a byte cell and passes
its address.

## Syscall numbers  (src: {UNISTD})

| name | __NR |
|---|---|
| sendmsg | {nr('sendmsg')} |
| recvmsg | {nr('recvmsg')} |
| sendto | {nr('sendto')} |
| recvfrom | {nr('recvfrom')} |

## Constants  (src: Python `socket` module)

| name | value |
|---|---|
| SOL_SOCKET | {socket.SOL_SOCKET} |
| SCM_RIGHTS | {socket.SCM_RIGHTS} |
| MSG_CMSG_CLOEXEC | {getattr(socket, 'MSG_CMSG_CLOEXEC', 'n/a')} |

## struct msghdr  (src: ctypes layout; LP64)  — total {ctypes.sizeof(msghdr)} bytes

| field | offset | size | note |
|---|---|---|---|
{tbl([(n, o, s, note) for (n, o, s), note in zip(layout(msghdr), [
    'ptr to sockaddr, 0 for connected socket',
    'socklen_t; 0 when name is 0 (note: 4 bytes, then 4 pad before msg_iov)',
    'ptr to iovec array (the ordinary payload bytes)',
    'iovec count',
    'ptr to the control buffer (the cmsghdr lives here)',
    'control buffer length = CMSG_SPACE(payload)',
    'flags; set on recv, 0 on send'])])}

## struct cmsghdr  (src: ctypes layout; LP64)  — header {CMSG_HDR_SIZE} bytes, then data

| field | offset | size | note |
|---|---|---|---|
{tbl([(n, o, s, note) for (n, o, s), note in zip(layout(cmsghdr), [
    'size_t; = CMSG_LEN(payload), covers header+data (NOT padded)',
    'int; = SOL_SOCKET for fd passing',
    'int; = SCM_RIGHTS for fd passing'])])}
| (data) | {CMSG_HDR_SIZE} | payload | the int fd(s); CMSG_DATA = cmsg + {CMSG_HDR_SIZE} |

## CMSG math for ONE fd  (payload = {ONE_FD} bytes; verified == Python's socket.CMSG_*)

| macro | value | meaning |
|---|---|---|
| CMSG_ALIGN(n) | (n+{SIZEOF_SIZE_T-1}) & ~{SIZEOF_SIZE_T-1} | round up to size_t |
| CMSG_LEN(4) | {cmsg_len(ONE_FD)} | goes in cmsg_len (header {CMSG_HDR_SIZE} + 4 data) |
| CMSG_SPACE(4) | {cmsg_space(ONE_FD)} | goes in msg_controllen; buffer bytes to reserve |

## The build, concretely (one fd, connected socket)

Control buffer is `CMSG_SPACE(4)` = {cmsg_space(ONE_FD)} bytes:
- `cmsg_len`   (off 0,  u64) = {cmsg_len(ONE_FD)}    (= CMSG_LEN(4))
- `cmsg_level` (off 8,  i32) = {socket.SOL_SOCKET}   (SOL_SOCKET)
- `cmsg_type`  (off 12, i32) = {socket.SCM_RIGHTS}   (SCM_RIGHTS)
- fd bytes     (off 16, i32) = the int fd

msghdr (name=0/namelen=0, one iovec of real payload, control=&cbuf,
controllen={cmsg_space(ONE_FD)}, flags=0), then `sendmsg(sockfd, &msg, flags)`.
Return: bytes of ordinary payload sent, or -errno.
"""

out = os.path.join(HERE, "ref-fdpass.md")
with open(out, "w") as f:
    f.write(doc)
print("wrote", out)
