#!/usr/bin/env python3
"""gen-clock.py — emit ref-clock.md (E32: clock_gettime / nanosleep / exit_group).

Local sources only, per examples/refs/README.md:
  - /usr/include/asm/unistd_64.h for syscall numbers when present;
    otherwise the pinned x86-64 Linux table, marked "pinned (header absent)".
  - Python `time` / `errno` modules for constants (live, this interpreter).
  - ctypes for the timespec field sizes/offsets (derived, this platform).

Usage: python3 gen-clock.py > ref-clock.md
"""
import ctypes, errno, os, re, sys, time

HDR = "/usr/include/asm/unistd_64.h"
PINNED = {"clock_gettime": 228, "nanosleep": 35, "exit_group": 231, "exit": 60}


def syscall_rows():
    rows = []
    text = None
    if os.path.exists(HDR):
        text = open(HDR).read()
    for name, pinned in PINNED.items():
        if text:
            m = re.search(rf"#define __NR_{name}\s+(\d+)", text)
            if m:
                rows.append((name, int(m.group(1)), f"`{HDR}`"))
                continue
        rows.append((name, pinned, "pinned (header absent; x86-64 Linux ABI)"))
    return rows


class Timespec(ctypes.Structure):
    _fields_ = [("tv_sec", ctypes.c_long), ("tv_nsec", ctypes.c_long)]


def main():
    out = []
    w = out.append
    w("# ref-clock — E32 ABI facts (x86-64 Linux)\n")
    w("Generated by `gen-clock.py`; re-run to re-derive. Sources per row.\n")

    w("## Syscall numbers\n")
    w("| call | nr | source |")
    w("|---|---|---|")
    for name, nr, src in syscall_rows():
        w(f"| {name} | {nr} | {src} |")
    w("")
    w("`exit_group` (231) ends the whole process — this is what the `exit` extern")
    w("wants; `exit` (60) ends one thread only.\n")

    w("## Constants\n")
    w("| name | value | source |")
    w("|---|---|---|")
    w(f"| CLOCK_MONOTONIC | {time.CLOCK_MONOTONIC} | `time.CLOCK_MONOTONIC` (live) |")
    w(f"| EINTR | {errno.EINTR} | `errno.EINTR` (live) |")
    w("")

    w("## struct timespec (derived via ctypes on this platform)\n")
    w("| field | ctype | offset | size |")
    w("|---|---|---|---|")
    for f, _ in Timespec._fields_:
        w(f"| {f} | c_long | {getattr(Timespec, f).offset} | {getattr(Timespec, f).size} |")
    w(f"\ntotal size: {ctypes.sizeof(Timespec)} bytes — two i64s, a 16-byte cell.\n")

    w("## Register convention (per-crossing)\n")
    w("| call | rdi | rsi | ret |")
    w("|---|---|---|---|")
    w("| clock_gettime | clockid (1) | timespec* (OUT) | 0 or -errno |")
    w("| nanosleep | req timespec* (IN) | rem timespec* (OUT, may be 0) | 0 or -errno (-EINTR ⇒ rem holds remainder) |")
    w("| exit_group | status | — | never returns |")
    w("")

    w("## ms ↔ timespec math\n")
    w("```")
    w("ms -> timespec:   tv_sec = ms / 1000        (Euclidean, ms >= 0)")
    w("                  tv_nsec = (ms % 1000) * 1000000")
    w("timespec -> ms:   ms = tv_sec * 1000 + tv_nsec / 1000000")
    w("```")
    w("nsec bound: tv_nsec in [0, 999999999] — the conversion above cannot")
    w("overflow it for ms >= 0. I64 ms overflows at ~292 million years of")
    w("uptime; carried as an honest non-limit.")
    print("\n".join(out))


if __name__ == "__main__":
    main()
