#!/usr/bin/env python3
"""gen-elf.py -- derive the ELF64 facts E34 needs, from LOCAL sources only.

Sources, per row:
  elf.h     -- /usr/include/elf.h (constants, by regex)
  struct    -- Python struct offset math over the canonical Elf64 field layout
  readelf   -- readelf -h/-l on a real local binary (cross-check values)
  derived   -- arithmetic over rows above (layout math for the minimal file)

Re-run to re-derive; every number in ref-elf.md traces to one of these.
Emits markdown on stdout. x86-64 Linux throughout.
"""
import re, shutil, struct, subprocess, sys

ELF_H = "/usr/include/elf.h"
BIN = "/bin/true"

def elf_h_const(name):
    try:
        text = open(ELF_H).read()
    except OSError:
        return None, "elf.h ABSENT"
    m = re.search(rf"#define\s+{name}\s+(\d+|0x[0-9a-fA-F]+)\b", text)
    if m:
        return int(m.group(1), 0), "elf.h"
    m = re.search(rf"#define\s+{name}\s+\(1\s*<<\s*(\d+)\)", text)
    if m:
        return 1 << int(m.group(1)), "elf.h (1<<n)"
    return None, f"elf.h: {name} not found"

def readelf(flag, path=BIN):
    if not shutil.which("readelf"):
        return None
    try:
        return subprocess.run(["readelf", flag, path], capture_output=True,
                              text=True, timeout=10).stdout
    except Exception:
        return None

# ---- Ehdr field layout: (name, fmt, note) in canonical order ----------------
EHDR = [
    ("e_ident",     "16s", "magic 7f 45 4c 46 ('\\x7fELF') + class/data/version/abi pad"),
    ("e_type",      "H",   "ET_EXEC for a static exec"),
    ("e_machine",   "H",   "EM_X86_64"),
    ("e_version",   "I",   "EV_CURRENT"),
    ("e_entry",     "Q",   "virtual entry address"),
    ("e_phoff",     "Q",   "phdr table file offset (right after ehdr: 64)"),
    ("e_shoff",     "Q",   "0 -- no sections in the minimal file"),
    ("e_flags",     "I",   "0 on x86-64"),
    ("e_ehsize",    "H",   "ehdr size"),
    ("e_phentsize", "H",   "one phdr entry size"),
    ("e_phnum",     "H",   "1 -- single PT_LOAD"),
    ("e_shentsize", "H",   "0 (no sections)"),
    ("e_shnum",     "H",   "0"),
    ("e_shstrndx",  "H",   "0"),
]
PHDR = [
    ("p_type",   "I", "PT_LOAD"),
    ("p_flags",  "I", "PF_R|PF_X for the one RX segment"),
    ("p_offset", "Q", "0 -- map the file from byte 0"),
    ("p_vaddr",  "Q", "load base (conventional 0x400000)"),
    ("p_paddr",  "Q", "= p_vaddr (unused on x86-64 Linux)"),
    ("p_filesz", "Q", "whole file: ehdr+phdr+code"),
    ("p_memsz",  "Q", "= p_filesz (no bss in minimal file)"),
    ("p_align",  "Q", "page size 0x1000"),
]

def offsets(rows):
    out, off = [], 0
    for name, fmt, note in rows:
        size = struct.calcsize("<" + fmt)
        out.append((name, off, size, note))
        off += size
    return out, off

def main():
    eh, ehsize = offsets(EHDR)
    ph, phsize = offsets(PHDR)

    consts = [
        ("ELFCLASS64",  "ELFCLASS64"), ("ELFDATA2LSB", "ELFDATA2LSB"),
        ("EV_CURRENT",  "EV_CURRENT"), ("ET_EXEC", "ET_EXEC"),
        ("EM_X86_64",   "EM_X86_64"),  ("PT_LOAD", "PT_LOAD"),
        ("PF_X", "PF_X"), ("PF_W", "PF_W"), ("PF_R", "PF_R"),
    ]

    print("# ref-elf -- ELF64 minimal static executable (x86-64 Linux)")
    print()
    print(f"Generated by `gen-elf.py`. Sources: `{ELF_H}`, Python `struct`,")
    print(f"`readelf` on `{BIN}`. Regenerate: `python3 gen-elf.py > ref-elf.md`.")
    print()
    print("## Constants (source: elf.h)")
    print()
    print("| name | value | source |")
    print("|---|---|---|")
    for label, name in consts:
        v, src = elf_h_const(name)
        vs = hex(v) if v is not None and v > 9 else str(v)
        print(f"| {label} | {vs} | {src} |")
    print()
    print(f"## Elf64_Ehdr -- {ehsize} bytes total (source: struct math; readelf cross-check below)")
    print()
    print("| field | offset | size | minimal-file value / note |")
    print("|---|---|---|---|")
    for name, off, size, note in eh:
        print(f"| {name} | {off} | {size} | {note} |")
    print()
    print(f"## Elf64_Phdr -- {phsize} bytes total (source: struct math)")
    print()
    print("| field | offset | size | minimal-file value / note |")
    print("|---|---|---|---|")
    for name, off, size, note in ph:
        print(f"| {name} | {off} | {size} | {note} |")
    print()
    print("## Minimal-file layout math (source: derived)")
    print()
    base = 0x400000
    code_off = ehsize + phsize
    print(f"- file = ehdr({ehsize}) + phdr({phsize}) + code; code file offset = {code_off} (0x{code_off:x})")
    print(f"- load base p_vaddr = 0x{base:x} (conventional); p_offset = 0; whole file mapped")
    print(f"- e_entry = p_vaddr + code_offset = 0x{base + code_off:x}")
    print(f"- p_filesz = p_memsz = {code_off} + len(code); p_align = 0x1000")
    print("- entry register state (System V psABI, x86-64): rsp -> [argc, argv...,")
    print("  NULL, envp..., NULL, auxv]; rdx = atexit fn or 0. argv/envp are STACK")
    print("  DATA at entry, not a syscall (the E32 env-get tie). Exit via syscall 60.")
    print()
    print("## readelf cross-check (source: readelf -h " + BIN + ")")
    print()
    out = readelf("-h")
    if out:
        keep = ("Magic", "Class", "Data", "Machine", "Version:",
                "Size of this header", "Size of program headers")
        for line in out.splitlines():
            if any(k in line for k in keep):
                print("    " + line.strip())
    else:
        print("    readelf ABSENT -- struct/elf.h rows stand alone")
    print()
    out = readelf("-l")
    if out:
        print("## PT_LOAD flags in the wild (source: readelf -l " + BIN + ")")
        print()
        for line in out.splitlines():
            if "LOAD" in line or "Align" in line and "0x" in line:
                print("    " + line.rstrip())
    print()

if __name__ == "__main__":
    sys.exit(main())
